name: demo-workflow-with-unpinned-versions
description: "Demo workflow that should trigger the github actions checker to update"

on:
  push:
    branches:
      - demo

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Check go version
        run: go version

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Setup java
        uses: actions/setup-java@main

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
